services:
  fayez.calculator.command.fayez:
    class: Fayez\Calculator\Command\CalculatorSumTwoIntegersCommand
    tags:
      -  { name: console.command }
    arguments:
      $a: '%fayez.a%'
      $b: '%fayez.b%'
